apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app
  labels:
    app: nodejs-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-web-app
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers:
      - name: nodejs-web-app
        image: ahm3dab/nodejs-web-app:latest
        ports:
        - containerPort: 3000
